// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: command.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED     CommandType = 0
	CommandType_COMMAND_TYPE_UNLOCK_DOORS    CommandType = 1
	CommandType_COMMAND_TYPE_LOCK_DOORS      CommandType = 2
	CommandType_COMMAND_TYPE_OPEN_FRUNK      CommandType = 3
	CommandType_COMMAND_TYPE_CLOSE_FRUNK     CommandType = 4
	CommandType_COMMAND_TYPE_OPEN_TRUNK      CommandType = 5
	CommandType_COMMAND_TYPE_CLOSE_TRUNK     CommandType = 6
	CommandType_COMMAND_TYPE_SET_SPEED_LIMIT CommandType = 7
	CommandType_COMMAND_TYPE_REBOOT_COMPUTER CommandType = 8
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_TYPE_UNLOCK_DOORS",
		2: "COMMAND_TYPE_LOCK_DOORS",
		3: "COMMAND_TYPE_OPEN_FRUNK",
		4: "COMMAND_TYPE_CLOSE_FRUNK",
		5: "COMMAND_TYPE_OPEN_TRUNK",
		6: "COMMAND_TYPE_CLOSE_TRUNK",
		7: "COMMAND_TYPE_SET_SPEED_LIMIT",
		8: "COMMAND_TYPE_REBOOT_COMPUTER",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":     0,
		"COMMAND_TYPE_UNLOCK_DOORS":    1,
		"COMMAND_TYPE_LOCK_DOORS":      2,
		"COMMAND_TYPE_OPEN_FRUNK":      3,
		"COMMAND_TYPE_CLOSE_FRUNK":     4,
		"COMMAND_TYPE_OPEN_TRUNK":      5,
		"COMMAND_TYPE_CLOSE_TRUNK":     6,
		"COMMAND_TYPE_SET_SPEED_LIMIT": 7,
		"COMMAND_TYPE_REBOOT_COMPUTER": 8,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_command_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_command_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0}
}

type VehicleCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`                 // Unique UUID for tracing
	Vin           string                 `protobuf:"bytes,2,opt,name=vin,proto3" json:"vin,omitempty"`                                              // Target vehicle VIN
	Type          CommandType            `protobuf:"varint,3,opt,name=type,proto3,enum=fleet.command.v1.CommandType" json:"type,omitempty"`         // Command enum action
	SpeedLimitMph float64                `protobuf:"fixed64,4,opt,name=speed_limit_mph,json=speedLimitMph,proto3" json:"speed_limit_mph,omitempty"` // Used when type is SET_SPEED_LIMIT
	TimestampMs   int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`          // Epoch timestamp (for replay attack prevention)
	Nonce         int64                  `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`                                         // Monotonic or cryptographic nonce
	Signature     []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`                                  // ECDSA signature of payload bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleCommand) Reset() {
	*x = VehicleCommand{}
	mi := &file_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleCommand) ProtoMessage() {}

func (x *VehicleCommand) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleCommand.ProtoReflect.Descriptor instead.
func (*VehicleCommand) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0}
}

func (x *VehicleCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *VehicleCommand) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *VehicleCommand) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *VehicleCommand) GetSpeedLimitMph() float64 {
	if x != nil {
		return x.SpeedLimitMph
	}
	return 0
}

func (x *VehicleCommand) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *VehicleCommand) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *VehicleCommand) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`          // Corresponds to the dispatched command ID
	Vin           string                 `protobuf:"bytes,2,opt,name=vin,proto3" json:"vin,omitempty"`                                       // Responding vehicle
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`                              // Whether the command succeeded
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error details if rejected (e.g., safety interlock or invalid signature)
	TimestampMs   int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`   // Execution acknowledgment timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResponse) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CommandResponse) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

var File_command_proto protoreflect.FileDescriptor

const file_command_proto_rawDesc = "" +
	"\n" +
	"\rcommand.proto\x12\x10fleet.command.v1\"\xf3\x01\n" +
	"\x0eVehicleCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x10\n" +
	"\x03vin\x18\x02 \x01(\tR\x03vin\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.fleet.command.v1.CommandTypeR\x04type\x12&\n" +
	"\x0fspeed_limit_mph\x18\x04 \x01(\x01R\rspeedLimitMph\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\x03R\x05nonce\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\"\xa4\x01\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x10\n" +
	"\x03vin\x18\x02 \x01(\tR\x03vin\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs*\xa1\x02\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19COMMAND_TYPE_UNLOCK_DOORS\x10\x01\x12\x1b\n" +
	"\x17COMMAND_TYPE_LOCK_DOORS\x10\x02\x12\x1b\n" +
	"\x17COMMAND_TYPE_OPEN_FRUNK\x10\x03\x12\x1c\n" +
	"\x18COMMAND_TYPE_CLOSE_FRUNK\x10\x04\x12\x1b\n" +
	"\x17COMMAND_TYPE_OPEN_TRUNK\x10\x05\x12\x1c\n" +
	"\x18COMMAND_TYPE_CLOSE_TRUNK\x10\x06\x12 \n" +
	"\x1cCOMMAND_TYPE_SET_SPEED_LIMIT\x10\a\x12 \n" +
	"\x1cCOMMAND_TYPE_REBOOT_COMPUTER\x10\bB>Z<github.com/itsnairr/fleet-telemetry-engine/internal/protocolb\x06proto3"

var (
	file_command_proto_rawDescOnce sync.Once
	file_command_proto_rawDescData []byte
)

func file_command_proto_rawDescGZIP() []byte {
	file_command_proto_rawDescOnce.Do(func() {
		file_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)))
	})
	return file_command_proto_rawDescData
}

var file_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_command_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_command_proto_goTypes = []any{
	(CommandType)(0),        // 0: fleet.command.v1.CommandType
	(*VehicleCommand)(nil),  // 1: fleet.command.v1.VehicleCommand
	(*CommandResponse)(nil), // 2: fleet.command.v1.CommandResponse
}
var file_command_proto_depIdxs = []int32{
	0, // 0: fleet.command.v1.VehicleCommand.type:type_name -> fleet.command.v1.CommandType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_command_proto_init() }
func file_command_proto_init() {
	if File_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_command_proto_goTypes,
		DependencyIndexes: file_command_proto_depIdxs,
		EnumInfos:         file_command_proto_enumTypes,
		MessageInfos:      file_command_proto_msgTypes,
	}.Build()
	File_command_proto = out.File
	file_command_proto_goTypes = nil
	file_command_proto_depIdxs = nil
}
